version: '3.8'

x-db-variables: &db-variables
 MYSQL_DATABASE: ${DB_SCHEMA}
 MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
 MYSQL_USER: ${DB_USER}
 MYSQL_PASSWORD: ${DB_PASSWORD}
 MYSQL_PORT: 3306

services:
  app:
    build: .
    image: gamer-ranking-system
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${DB_URL_INTERNAL}
      SPRING_DATASOURCE_DATABASE: ${DB_SCHEMA}
      SPRING_DATASOURCE_ROOT_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_PORT: 3306
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
     <<: *db-variables

volumes:
  gamer-ranking-db-volume: