version: "3.8"
services:
  app:
    build: .
    restart: on-failure
    ports:
      - 8080:8080
  #   depends_on:
  #     - databaseMySQL:

  # databaseMySQL:
  #   platform: linux/x86_64
  #   image: "mysql:8.0"
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_DATABASE: gamerrankingdb
  #     MYSQL_USER: gamer
  #     MYSQL_PASSWORD: G@m3rz
  #     MYSQL_ROOT_PASSWORD: turtl310
